export const testimonials = [
  {
    id: 1,
    name: "Sarah Mitchell",
    country: "USA",
    countryCode: "US",
    role: "Parent",
    rating: 5,
    text: "My son now reads Quran confidently after just 3 months with Ustadh Ibrahim. His patience with kids is remarkable.",
    image: "/images/testimonials/student-1.webp",
  },
  {
    id: 2,
    name: "James Abdullah",
    country: "UK",
    countryCode: "GB",
    role: "Revert",
    rating: 5,
    text: "As a new Muslim, I was nervous about learning. Tajwedo made me feel completely at ease and guided me beautifully.",
    image: "/images/testimonials/student-2.webp",
  },
  {
    id: 3,
    name: "Fatima van der Berg",
    country: "Netherlands",
    countryCode: "NL",
    role: "Adult Student",
    rating: 5,
    text: "The Tajweed lessons transformed my recitation completely. Tajwedo explains complex rules in such a simple way.",
    image: "/images/testimonials/student-3.webp",
  },
  {
    id: 4,
    name: "Ahmed Hassan",
    country: "Canada",
    countryCode: "CA",
    role: "Adult Student",
    rating: 5,
    text: "I have tried many online Quran teachers before, but Ibrahim is by far the best. His methodology is clear and effective.",
    image: "/images/testimonials/student-1.webp",
  },
  {
    id: 5,
    name: "Emily Roberts",
    country: "Australia",
    countryCode: "AU",
    role: "Parent",
    rating: 5,
    text: "Both my daughters love their weekly lessons with Ustadh Ibrahim. He makes learning Quran enjoyable and meaningful.",
    image: "/images/testimonials/student-2.webp",
  },
];
